name: 'Send a message on slack'
description: 'Creates a message in the channel by a webhook'
inputs:
    slack_webhook_url:
        description: 'Webhook URL (with channel and token)'
        required: true
    message:
        description: 'the message that will be posted'
        required: true
    is_markdown:
        description: 'Optional: is the message in markdown format (default: false)'
        required: false
runs:
    using: 'node16'
    main: 'dist/index.js'
